# https://dev.to/code42cate/how-to-dockerize-sveltekit-3oho

# Use a Node.js Alpine image for the builder stage
FROM node:22-alpine AS builder
RUN apk update
RUN apk add cargo pkgconfig openssl-dev
RUN cargo install cargo-watch
RUN cargo install wasm-pack
RUN cargo install --git https://github.com/oeb25/abeye --locked
WORKDIR /app
COPY . .
WORKDIR /app/frontend
RUN npm ci
ENV PATH="/root/.cargo/bin:$PATH"
RUN echo "$PATH"
# cargo-watch -s wasm-pack build --target web

RUN npm run build
RUN npm prune --production

## Use another Node.js Alpine image for the final stage
FROM node:22-alpine
WORKDIR /app/frontend
COPY --from=builder /app/frontend/build build/
COPY --from=builder /app/frontend/node_modules node_modules/
COPY frontend/package.json .
EXPOSE 3000
ENV NODE_ENV=production
CMD [ "node", "build" ]
